export const tableData = [
  {
    Customer: "Logitech Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 10674,
    GP: 3930,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 249,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "Logitech Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2061,
    GP: 1205,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 126,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "Logitech Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 52991,
    GP: 211,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 226,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "Logitech Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2112,
    GP: 126,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 459,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "Kohler Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 14948,
    GP: 2797,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 172,
    "Lead owner": "Rebecca WONG",
    "Lead owner station": "DIMHKG"
  },
  {
    Customer: "Kohler Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2257,
    GP: 1423,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 119,
    "Lead owner": "Rebecca WONG",
    "Lead owner station": "DIMHKG"
  },
  {
    Customer: "Kohler Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 68206,
    GP: 238,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 173,
    "Lead owner": "Rebecca WONG",
    "Lead owner station": "DIMHKG"
  },
  {
    Customer: "Kohler Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2577,
    GP: 136,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 500,
    "Lead owner": "Rebecca WONG",
    "Lead owner station": "DIMHKG"
  },
  {
    Customer: "TDK Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 14312,
    GP: 3162,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 225,
    "Lead owner": "Magie Yin",
    "Lead owner station": "ZJDTSN"
  },
  {
    Customer: "TDK Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2616,
    GP: 1486,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 141,
    "Lead owner": "Magie Yin",
    "Lead owner station": "ZJDTSN"
  },
  {
    Customer: "TDK Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 71290,
    GP: 249,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 193,
    "Lead owner": "Magie Yin",
    "Lead owner station": "ZJDTSN"
  },
  {
    Customer: "TDK Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2676,
    GP: 148,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 500,
    "Lead owner": "Magie Yin",
    "Lead owner station": "ZJDTSN"
  },
  {
    Customer: "CAL-Comp Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 12933,
    GP: 3513,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 169,
    "Lead owner": "Cillia Xu",
    "Lead owner station": "DIMSHA"
  },
  {
    Customer: "CAL-Comp Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2522,
    GP: 1205,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 137,
    "Lead owner": "Cillia Xu",
    "Lead owner station": "DIMSHA"
  },
  {
    Customer: "CAL-Comp Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 63456,
    GP: 236,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 247,
    "Lead owner": "Cillia Xu",
    "Lead owner station": "DIMSHA"
  },
  {
    Customer: "CAL-Comp Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2061,
    GP: 131,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 414,
    "Lead owner": "Cillia Xu",
    "Lead owner station": "DIMSHA"
  },
  {
    Customer: "BrightPoint Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 11702,
    GP: 2868,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 244,
    "Lead owner": "Grace Wu",
    "Lead owner station": "ZJDCAN"
  },
  {
    Customer: "BrightPoint Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2042,
    GP: 1242,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 104,
    "Lead owner": "Grace Wu",
    "Lead owner station": "ZJDCAN"
  },
  {
    Customer: "BrightPoint Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 57610,
    GP: 200,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 220,
    "Lead owner": "Grace Wu",
    "Lead owner station": "ZJDCAN"
  },
  {
    Customer: "BrightPoint Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2714,
    GP: 154,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 473,
    "Lead owner": "Grace Wu",
    "Lead owner station": "ZJDCAN"
  },
  {
    Customer: "Toyota Tsusho Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 14686,
    GP: 2853,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 244,
    "Lead owner": "Grace Wu",
    "Lead owner station": "ZJDCAN"
  },
  {
    Customer: "Toyota Tsusho Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2259,
    GP: 1166,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 111,
    "Lead owner": "Grace Wu",
    "Lead owner station": "ZJDCAN"
  },
  {
    Customer: "Toyota Tsusho Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 53456,
    GP: 234,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 195,
    "Lead owner": "Grace Wu",
    "Lead owner station": "ZJDCAN"
  },
  {
    Customer: "Toyota Tsusho Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2428,
    GP: 119,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 494,
    "Lead owner": "Grace Wu",
    "Lead owner station": "ZJDCAN"
  },
  {
    Customer: "Iventec Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 14316,
    GP: 3627,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 220,
    "Lead owner": "Peggie TAI",
    "Lead owner station": "DIMHKG"
  },
  {
    Customer: "Iventec Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2298,
    GP: 1516,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 129,
    "Lead owner": "Peggie TAI",
    "Lead owner station": "DIMHKG"
  },
  {
    Customer: "Iventec Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 66445,
    GP: 199,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 238,
    "Lead owner": "Peggie TAI",
    "Lead owner station": "DIMHKG"
  },
  {
    Customer: "Iventec Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 1978,
    GP: 151,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 503,
    "Lead owner": "Peggie TAI",
    "Lead owner station": "DIMHKG"
  },
  {
    Customer: "Gexpro Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 11706,
    GP: 3173,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 188,
    "Lead owner": "Ricks WAN",
    "Lead owner station": "DIMHKG"
  },
  {
    Customer: "Gexpro Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2621,
    GP: 1098,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 146,
    "Lead owner": "Ricks WAN",
    "Lead owner station": "DIMHKG"
  },
  {
    Customer: "Gexpro Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 63353,
    GP: 230,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 224,
    "Lead owner": "Ricks WAN",
    "Lead owner station": "DIMHKG"
  },
  {
    Customer: "Gexpro Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2196,
    GP: 156,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 503,
    "Lead owner": "Ricks WAN",
    "Lead owner station": "DIMHKG"
  },
  {
    Customer: "Cooler Master",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 13835,
    GP: 2915,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 173,
    "Lead owner": "Author Ji",
    "Lead owner station": "DIMSEL"
  },
  {
    Customer: "Cooler Master",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2698,
    GP: 1125,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 142,
    "Lead owner": "Author Ji",
    "Lead owner station": "DIMSEL"
  },
  {
    Customer: "Cooler Master",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 75212,
    GP: 224,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 254,
    "Lead owner": "Author Ji",
    "Lead owner station": "DIMSEL"
  },
  {
    Customer: "Cooler Master",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2734,
    GP: 119,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 350,
    "Lead owner": "Author Ji",
    "Lead owner station": "DIMSEL"
  },
  {
    Customer: "SAMSUNG SEC Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 13372,
    GP: 2850,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 174,
    "Lead owner": "Tim Kang",
    "Lead owner station": "ZJDBJS"
  },
  {
    Customer: "SAMSUNG SEC Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2710,
    GP: 1561,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 129,
    "Lead owner": "Tim Kang",
    "Lead owner station": "ZJDBJS"
  },
  {
    Customer: "SAMSUNG SEC Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 53291,
    GP: 238,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 180,
    "Lead owner": "Tim Kang",
    "Lead owner station": "ZJDBJS"
  },
  {
    Customer: "SAMSUNG SEC Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 1890,
    GP: 155,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 384,
    "Lead owner": "Tim Kang",
    "Lead owner station": "ZJDBJS"
  },
  {
    Customer: "SAMSUNG SEMCO Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 11711,
    GP: 3052,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 171,
    "Lead owner": "Tim Kang",
    "Lead owner station": "ZJDBJS"
  },
  {
    Customer: "SAMSUNG SEMCO Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2074,
    GP: 1109,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 131,
    "Lead owner": "Tim Kang",
    "Lead owner station": "ZJDBJS"
  },
  {
    Customer: "SAMSUNG SEMCO Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 66969,
    GP: 229,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 179,
    "Lead owner": "Tim Kang",
    "Lead owner station": "ZJDBJS"
  },
  {
    Customer: "SAMSUNG SEMCO Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2186,
    GP: 140,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 469,
    "Lead owner": "Tim Kang",
    "Lead owner station": "ZJDBJS"
  },
  {
    Customer: "Elo Touch Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 12003,
    GP: 3615,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 236,
    "Lead owner": "Steven Jin",
    "Lead owner station": "ZJDLFA"
  },
  {
    Customer: "Elo Touch Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2321,
    GP: 1151,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 108,
    "Lead owner": "Steven Jin",
    "Lead owner station": "ZJDLFA"
  },
  {
    Customer: "Elo Touch Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 69115,
    GP: 244,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 226,
    "Lead owner": "Steven Jin",
    "Lead owner station": "ZJDLFA"
  },
  {
    Customer: "Elo Touch Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2554,
    GP: 132,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 471,
    "Lead owner": "Steven Jin",
    "Lead owner station": "ZJDLFA"
  },
  {
    Customer: "Richardson Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 14807,
    GP: 2819,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 224,
    "Lead owner": "Vivian Sun",
    "Lead owner station": "DIMSIA"
  },
  {
    Customer: "Richardson Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2456,
    GP: 1236,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 142,
    "Lead owner": "Vivian Sun",
    "Lead owner station": "DIMSIA"
  },
  {
    Customer: "Richardson Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 65143,
    GP: 196,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 217,
    "Lead owner": "Vivian Sun",
    "Lead owner station": "DIMSIA"
  },
  {
    Customer: "Richardson Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2407,
    GP: 114,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 507,
    "Lead owner": "Vivian Sun",
    "Lead owner station": "DIMSIA"
  },
  {
    Customer: "Ideal Box Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 10796,
    GP: 2630,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 240,
    "Lead owner": "Dylan Lee",
    "Lead owner station": "DFSTPE"
  },
  {
    Customer: "Ideal Box Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2514,
    GP: 1267,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 113,
    "Lead owner": "Dylan Lee",
    "Lead owner station": "DFSTPE"
  },
  {
    Customer: "Ideal Box Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 61369,
    GP: 223,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 245,
    "Lead owner": "Dylan Lee",
    "Lead owner station": "DFSTPE"
  },
  {
    Customer: "Ideal Box Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2554,
    GP: 120,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 476,
    "Lead owner": "Dylan Lee",
    "Lead owner station": "DFSTPE"
  },
  {
    Customer: "Microfibres Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 14400,
    GP: 3865,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 175,
    "Lead owner": "Vinky Chen",
    "Lead owner station": "ZJDXMN"
  },
  {
    Customer: "Microfibres Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2748,
    GP: 1524,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 139,
    "Lead owner": "Vinky Chen",
    "Lead owner station": "ZJDXMN"
  },
  {
    Customer: "Microfibres Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 61070,
    GP: 211,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 238,
    "Lead owner": "Vinky Chen",
    "Lead owner station": "ZJDXMN"
  },
  {
    Customer: "Microfibres Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2475,
    GP: 114,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 506,
    "Lead owner": "Vinky Chen",
    "Lead owner station": "ZJDXMN"
  },
  {
    Customer: "Lam Research Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 14679,
    GP: 2992,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 240,
    "Lead owner": "Diva Tsao",
    "Lead owner station": "DFSTPE"
  },
  {
    Customer: "Lam Research Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2380,
    GP: 1099,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 119,
    "Lead owner": "Diva Tsao",
    "Lead owner station": "DFSTPE"
  },
  {
    Customer: "Lam Research Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 65883,
    GP: 231,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 253,
    "Lead owner": "Diva Tsao",
    "Lead owner station": "DFSTPE"
  },
  {
    Customer: "Lam Research Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2544,
    GP: 156,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 455,
    "Lead owner": "Diva Tsao",
    "Lead owner station": "DFSTPE"
  },
  {
    Customer: "CAMPING WORLD Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 11523,
    GP: 2789,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 183,
    "Lead owner": "Vinky Chen",
    "Lead owner station": "ZJDXMN"
  },
  {
    Customer: "CAMPING WORLD Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2237,
    GP: 1309,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 110,
    "Lead owner": "Vinky Chen",
    "Lead owner station": "ZJDXMN"
  },
  {
    Customer: "CAMPING WORLD Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 76674,
    GP: 240,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 221,
    "Lead owner": "Vinky Chen",
    "Lead owner station": "ZJDXMN"
  },
  {
    Customer: "CAMPING WORLD Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2249,
    GP: 147,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 483,
    "Lead owner": "Vinky Chen",
    "Lead owner station": "ZJDXMN"
  },
  {
    Customer: "Air Delivery Express Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 15444,
    GP: 3875,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 214,
    "Lead owner": "Diva Tsao",
    "Lead owner station": "DFSTPE"
  },
  {
    Customer: "Air Delivery Express Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 1860,
    GP: 1189,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 146,
    "Lead owner": "Diva Tsao",
    "Lead owner station": "DFSTPE"
  },
  {
    Customer: "Air Delivery Express Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 67800,
    GP: 216,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 199,
    "Lead owner": "Diva Tsao",
    "Lead owner station": "DFSTPE"
  },
  {
    Customer: "Air Delivery Express Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2653,
    GP: 155,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 442,
    "Lead owner": "Diva Tsao",
    "Lead owner station": "DFSTPE"
  },
  {
    Customer: "onsemi",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 15019,
    GP: 2718,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 228,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "onsemi",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2254,
    GP: 1118,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 147,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "onsemi",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 65908,
    GP: 195,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 250,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "onsemi",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2222,
    GP: 110,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 510,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "Kingston",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 13124,
    GP: 2908,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 204,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "Kingston",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2695,
    GP: 1414,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 108,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "Kingston",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 67009,
    GP: 232,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 241,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "Kingston",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2511,
    GP: 111,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 496,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "Advanced Energy",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 12373,
    GP: 3797,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 213,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "Advanced Energy",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 2438,
    GP: 1112,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 99,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DFSSHA"
  },
  {
    Customer: "Advanced Energy",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 73365,
    GP: 276,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 188,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "Advanced Energy",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 2135,
    GP: 116,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 445,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DFSSHA"
  },
  {
    Customer: "Advanced Energy",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 12373,
    GP: 3797,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 213,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "Advanced Energy",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2438,
    GP: 1112,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 99,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "Advanced Energy",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 73365,
    GP: 276,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 188,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DFSSHA"
  },
  {
    Customer: "Advanced Energy",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2135,
    GP: 116,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 445,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DFSSHA"
  },
  {
    Customer: "GoPro Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 15513,
    GP: 3091,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 166,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "GoPro Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2590,
    GP: 1366,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 108,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "GoPro Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 55876,
    GP: 238,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 237,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "GoPro Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2525,
    GP: 106,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 462,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "BroadCom Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 14514,
    GP: 3113,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 190,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "BroadCom Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 1951,
    GP: 1343,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 123,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "BroadCom Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 61202,
    GP: 189,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 203,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "BroadCom Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2181,
    GP: 143,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 361,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "Qualcomm Project",
    YYYYMM: 202501,
    Mode: "AE",
    Revenue: 11265,
    GP: 3621,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 244,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "Qualcomm Project",
    YYYYMM: 202501,
    Mode: "AI",
    Revenue: 2031,
    GP: 1058,
    Ori_Country: "TW",
    Origin: "TPE",
    DSTN_Country: "CN",
    Destination: "SHA",
    "Shipment count": 106,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "Qualcomm Project",
    YYYYMM: 202501,
    Mode: "OE",
    Revenue: 61201,
    GP: 250,
    Ori_Country: "CN",
    Origin: "SHA",
    DSTN_Country: "US",
    Destination: "LAX",
    "Shipment count": 183,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  },
  {
    Customer: "Qualcomm Project",
    YYYYMM: 202501,
    Mode: "OI",
    Revenue: 2348,
    GP: 131,
    Ori_Country: "CN",
    Origin: "CAN",
    DSTN_Country: "US",
    Destination: "ORD",
    "Shipment count": 359,
    "Lead owner": "JuJu Huang",
    "Lead owner station": "DIMTPE"
  }
];
