const GetCustomerQuickFilterColumnList = 1,
  CustomizeQuickFilterSettingFromCustomerSearch = 2,
  CustomerGridColumnSetting = 3,
  CustomerGridResult = 4,
  CustomerProfileColumnList = 5,
  GetQuoteQuickFilterColumnList = 70,
  CustomizeQuickFilterSettingFromQuoteSearch = 71,
  QuoteGridColumnSetting = 72,
  QuoteGridResult = 73,
  QuoteDetailColumnAccessRight = 205,
  AirCity = 9,
  AirPort = 10,
  SeaCity = 11,
  SeaPort = 12,
  GetContactQuickFilterColumnList = 21,
  CustomizeQuickFilterSettingFromContactSearch = 22,
  ContactGridColumnSetting = 23,
  ContactGridResult = 24,
  ContactProfileColumnList = 25,
  GetTaskQuickFilterColumnList = 31,
  CustomizeQuickFilterSettingFromTaskSearch = 32,
  TaskGridColumnSetting = 33,
  TaskGridResult = 34,
  TaskProfileColumnList = 35,
  GetApprovalFilterColumnList = 41,
  CustomizeQuickFilterSettingFromApprovalSearch = 42,
  ApprovalGridColumnSetting = 43,
  ApprovalGridResult = 44,
  ApprovalColumnList = 45;

export {
  GetCustomerQuickFilterColumnList,
  CustomizeQuickFilterSettingFromCustomerSearch,
  CustomerGridColumnSetting,
  CustomerGridResult,
  CustomerProfileColumnList,
  GetQuoteQuickFilterColumnList,
  CustomizeQuickFilterSettingFromQuoteSearch,
  QuoteGridColumnSetting,
  QuoteGridResult,
  QuoteDetailColumnAccessRight,
  AirCity,
  AirPort,
  SeaCity,
  SeaPort,
  GetContactQuickFilterColumnList,
  CustomizeQuickFilterSettingFromContactSearch,
  ContactGridColumnSetting,
  ContactGridResult,
  ContactProfileColumnList,
  GetTaskQuickFilterColumnList,
  CustomizeQuickFilterSettingFromTaskSearch,
  TaskGridColumnSetting,
  TaskGridResult,
  TaskProfileColumnList,
  GetApprovalFilterColumnList,
  CustomizeQuickFilterSettingFromApprovalSearch,
  ApprovalGridColumnSetting,
  ApprovalGridResult,
  ApprovalColumnList
};
