const customerName = 0,
  customerStatus = 1,
  productLine = 2,
  carrier = 3,
  shipper = 4,
  consignee = 5,
  tradeterm = 6,
  quotestatus = 7,
  shippingterm = 8,
  servicelevel = 9,
  natureofgoods = 10,
  shipmentqualitytype = 11,
  creditterm = 12,
  quoteProductLine = 13,
  country = 14,
  state = 15,
  city = 16,
  leadSourceGroup = 17,
  industryGroup = 18,
  status = 19,
  quoteCustomerByLead = 20,
  quoteFreightChargeCode = 21,
  dimOrg = 22,
  leadSource = 100,
  leadSourceDetail = 101,
  industry = 102,
  currency = 103,
  agentRO = 104,
  user = 105,
  countryBySearchKey = 106,
  stateBySearchKey = 107,
  cityBySearchKey = 108,
  leadSourceGroupBySearchKey = 109,
  industryGroupBySearchKey = 110,
  localName = 111,
  userBySearchKey = 112,
  leadSourceBySearchKey = 113,
  leadSourceDetailBySearchKey = 114,
  industryBySearchKey = 115,
  ownerSales = 116,
  station = 117,
  contactNames = 118,
  contactFullName = 119,
  contactRole = 120,
  contactBoss = 121,
  contactHobby = 122,
  taskPriority = 123,
  taskLogType = 124,
  taskStatus = 125,
  taskSubjectType = 126,
  userformat2 = 127,
  cityformat2BySearchKey = 128,
  contactBycustomerid = 129,
  stationCustID = 130;

export {
  customerName,
  customerStatus,
  productLine,
  carrier,
  shipper,
  consignee,
  tradeterm,
  quotestatus,
  shippingterm,
  servicelevel,
  natureofgoods,
  shipmentqualitytype,
  creditterm,
  quoteProductLine,
  country,
  state,
  city,
  leadSourceGroup,
  industryGroup,
  status,
  quoteCustomerByLead,
  quoteFreightChargeCode,
  dimOrg,
  leadSource,
  leadSourceDetail,
  industry,
  currency,
  agentRO,
  user,
  countryBySearchKey,
  stateBySearchKey,
  cityBySearchKey,
  leadSourceGroupBySearchKey,
  industryGroupBySearchKey,
  localName,
  userBySearchKey,
  leadSourceBySearchKey,
  leadSourceDetailBySearchKey,
  industryBySearchKey,
  ownerSales,
  station,
  contactNames,
  contactFullName,
  contactRole,
  contactBoss,
  contactHobby,
  taskPriority,
  taskLogType,
  taskStatus,
  taskSubjectType,
  userformat2,
  cityformat2BySearchKey,
  contactBycustomerid,
  stationCustID
};
